In [1]:
import pandas as pd
import numpy as np
from pathlib import Path

In [2]:
PROJECT_ROOT= Path.cwd().parent
PROJECT_ROOT

WindowsPath('c:/Users/ganesh/Desktop/All Projects/Build Logistic Analysis Project')

In [3]:
DATA_PATH= PROJECT_ROOT / "data" / "APL_Logistics.csv"
DATA_PATH

WindowsPath('c:/Users/ganesh/Desktop/All Projects/Build Logistic Analysis Project/data/APL_Logistics.csv')

In [4]:
df= pd.read_csv(DATA_PATH, encoding="Latin1")
df

,Type,Days for shipping (real),Days for shipment (scheduled),Benefit per order,Sales per customer,Delivery Status,Late_delivery_risk,Category Id,Category Name,Customer City,...,Order Item Quantity,Sales,Order Item Total,Order Profit Per Order,Order Region,Order State,Order Status,Product Name,Product Price,Shipping Mode
0,DEBIT,6,4,159.69,472.45,Late delivery,1,9,Cardio Equipment,Brownsville,...,5,499.95,472.45,159.69,South Asia,Maharashtra,COMPLETE,Nike Men's Free 5.0+ Running Shoe,99.99,Standard Class
1,DEBIT,4,4,48.71,167.96,Shipping on time,0,29,Shop By Sport,Littleton,...,5,199.95,167.96,48.71,Central America,Cortés,ON_HOLD,Under Armour Girls' Toddler Spine Surge Runni,39.99,Standard Class
2,DEBIT,4,4,87.36,181.99,Shipping on time,0,48,Water Sports,Littleton,...,1,199.99,181.99,87.36,Central America,Cortés,ON_HOLD,Pelican Sunstream 100 Kayak,199.99,Standard Class
3,DEBIT,6,4,-41.89,175.99,Late delivery,1,48,Water Sports,Littleton,...,1,199.99,175.99,-41.89,East of USA,Nueva York,COMPLETE,Pelican Sunstream 100 Kayak,199.99,Standard Class
4,DEBIT,6,4,10.00,40.00,Late delivery,1,24,Women's Apparel,Littleton,...,1,50.00,40.00,10.00,East of USA,Nueva York,COMPLETE,Nike Men's Dri-FIT Victory Golf Polo,50.00,Standard Class
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
180514,TRANSFER,6,4,-107.96,161.87,Late delivery,1,76,Women's Clothing,Caguas,...,1,215.82,161.87,-107.96,Southeast Asia,Java Occidental,PROCESSING,Summer dresses,215.82,Standard Class
180515,DEBIT,2,4,-126.56,172.66,Advance shipping,0,76,Women's Clothing,Plainfield,...,1,215.82,172.66,-126.56,Southeast Asia,Java Occidental,COMPLETE,Summer dresses,215.82,Standard Class
180516,DEBIT,3,4,91.25,314.64,Advance shipping,0,73,Sporting Goods,Caguas,...,1,327.75,314.64,91.25,Southeast Asia,Java Occidental,COMPLETE,Smart watch,327.75,Standard Class
180517,PAYMENT,4,4,1.53,10.91,Shipping on time,0,74,Toys,Berwyn,...,1,11.54,10.91,1.53,Southeast Asia,Java Occidental,PENDING_PAYMENT,Toys,11.54,Standard Class
180518,CASH,1,0,9.79,34.98,Late delivery,1,75,Video Games,Miami,...,1,39.75,34.98,9.79,Oceania,Queensland,CLOSED,Fighting video games,39.75,Same Day

In [5]:
df.head()

,Type,Days for shipping (real),Days for shipment (scheduled),Benefit per order,Sales per customer,Delivery Status,Late_delivery_risk,Category Id,Category Name,Customer City,...,Order Item Quantity,Sales,Order Item Total,Order Profit Per Order,Order Region,Order State,Order Status,Product Name,Product Price,Shipping Mode
0,DEBIT,6,4,159.69,472.45,Late delivery,1,9,Cardio Equipment,Brownsville,...,5,499.95,472.45,159.69,South Asia,Maharashtra,COMPLETE,Nike Men's Free 5.0+ Running Shoe,99.99,Standard Class
1,DEBIT,4,4,48.71,167.96,Shipping on time,0,29,Shop By Sport,Littleton,...,5,199.95,167.96,48.71,Central America,Cortés,ON_HOLD,Under Armour Girls' Toddler Spine Surge Runni,39.99,Standard Class
2,DEBIT,4,4,87.36,181.99,Shipping on time,0,48,Water Sports,Littleton,...,1,199.99,181.99,87.36,Central America,Cortés,ON_HOLD,Pelican Sunstream 100 Kayak,199.99,Standard Class
3,DEBIT,6,4,-41.89,175.99,Late delivery,1,48,Water Sports,Littleton,...,1,199.99,175.99,-41.89,East of USA,Nueva York,COMPLETE,Pelican Sunstream 100 Kayak,199.99,Standard Class
4,DEBIT,6,4,10.00,40.00,Late delivery,1,24,Women's Apparel,Littleton,...,1,50.00,40.00,10.00,East of USA,Nueva York,COMPLETE,Nike Men's Dri-FIT Victory Golf Polo,50.00,Standard Class

In [6]:
df.shape

(180519, 40)

In [7]:
df.columns.tolist()

['Type',
 'Days for shipping (real)',
 'Days for shipment (scheduled)',
 'Benefit per order',
 'Sales per customer',
 'Delivery Status',
 'Late_delivery_risk',
 'Category Id',
 'Category Name',
 'Customer City',
 'Customer Country',
 'Customer Fname',
 'Customer Id',
 'Customer Lname',
 'Customer Segment',
 'Customer State',
 'Customer Street',
 'Customer Zipcode',
 'Department Id',
 'Department Name',
 'Latitude',
 'Longitude',
 'Market',
 'Order City',
 'Order Country',
 'Order Customer Id',
 'Order Item Discount',
 'Order Item Discount Rate',
 'Order Item Product Price',
 'Order Item Profit Ratio',
 'Order Item Quantity',
 'Sales',
 'Order Item Total',
 'Order Profit Per Order',
 'Order Region',
 'Order State',
 'Order Status',
 'Product Name',
 'Product Price',
 'Shipping Mode']

In [8]:
df.dtypes

Type                                 str
Days for shipping (real)           int64
Days for shipment (scheduled)      int64
Benefit per order                float64
Sales per customer               float64
Delivery Status                      str
Late_delivery_risk                 int64
Category Id                        int64
Category Name                        str
Customer City                        str
Customer Country                     str
Customer Fname                       str
Customer Id                        int64
Customer Lname                       str
Customer Segment                     str
Customer State                       str
Customer Street                      str
Customer Zipcode                 float64
Department Id                      int64
Department Name                      str
Latitude                         float64
Longitude                        float64
Market                               str
Order City                           str
Order Country                        str
Order Customer Id                  int64
Order Item Discount              float64
Order Item Discount Rate         float64
Order Item Product Price         float64
Order Item Profit Ratio          float64
Order Item Quantity                int64
Sales                            float64
Order Item Total                 float64
Order Profit Per Order           float64
Order Region                         str
Order State                          str
Order Status                         str
Product Name                         str
Product Price                    float64
Shipping Mode                        str
dtype: object

In [9]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 180519 entries, 0 to 180518
Data columns (total 40 columns):
 #   Column                         Non-Null Count   Dtype
---  ------                         --------------   -----
 0   Type                           180519 non-null  str
 1   Days for shipping (real)       180519 non-null  int64
 2   Days for shipment (scheduled)  180519 non-null  int64
 3   Benefit per order              180519 non-null  float64
 4   Sales per customer             180519 non-null  float64
 5   Delivery Status                180519 non-null  str
 6   Late_delivery_risk             180519 non-null  int64
 7   Category Id                    180519 non-null  int64
 8   Category Name                  180519 non-null  str
 9   Customer City                  180519 non-null  str
 10  Customer Country               180519 non-null  str
 11  Customer Fname                 180519 non-null  str
 12  Customer Id                    180519 non-null  int64
 13  Customer Lname                 180511 non-null  str
 14  Customer Segment               180519 non-null  str
 15  Customer State                 180519 non-null  str
 16  Customer Street                180519 non-null  str
 17  Customer Zipcode               180516 non-null  float64
 18  Department Id                  180519 non-null  int64
 19  Department Name                180519 non-null  str
 20  Latitude                       180519 non-null  float64
 21  Longitude                      180519 non-null  float64
 22  Market                         180519 non-null  str
 23  Order City                     180519 non-null  str
 24  Order Country                  180519 non-null  str
 25  Order Customer Id              180519 non-null  int64
 26  Order Item Discount            180519 non-null  float64
 27  Order Item Discount Rate       180519 non-null  float64
 28  Order Item Product Price       180519 non-null  float64
 29  Order Item Profit Ratio        180519 non-null  float64
 30  Order Item Quantity            180519 non-null  int64
 31  Sales                          180519 non-null  float64
 32  Order Item Total               180519 non-null  float64
 33  Order Profit Per Order         180519 non-null  float64
 34  Order Region                   180519 non-null  str
 35  Order State                    180519 non-null  str
 36  Order Status                   180519 non-null  str
 37  Product Name                   180519 non-null  str
 38  Product Price                  180519 non-null  float64
 39  Shipping Mode                  180519 non-null  str
dtypes: float64(13), int64(8), str(19)
memory usage: 90.2 MB

In [10]:
df.describe()

,Days for shipping (real),Days for shipment (scheduled),Benefit per order,Sales per customer,Late_delivery_risk,Category Id,Customer Id,Customer Zipcode,Department Id,Latitude,...,Order Customer Id,Order Item Discount,Order Item Discount Rate,Order Item Product Price,Order Item Profit Ratio,Order Item Quantity,Sales,Order Item Total,Order Profit Per Order,Product Price
count,180519.000000,180519.000000,180519.000000,180519.000000,180519.000000,180519.000000,180519.000000,180516.000000,180519.000000,180519.000000,...,180519.000000,180519.000000,180519.000000,180519.000000,180519.000000,180519.000000,180519.000000,180519.000000,180519.000000,180519.000000
mean,3.497654,2.931847,21.974989,183.107607,0.548291,31.851451,6691.379495,35921.126914,5.443460,29.719955,...,6691.379495,20.664741,0.101668,141.232547,0.120647,2.127638,203.772092,183.107607,21.974989,141.232547
std,1.623722,1.374449,104.433526,120.043668,0.497664,15.640064,4162.918106,37542.461122,1.629246,9.813646,...,4162.918106,21.800901,0.070415,139.732489,0.466796,1.453451,132.273075,120.043668,104.433526,139.732489
min,0.000000,0.000000,-4274.980000,7.490000,0.000000,2.000000,1.000000,603.000000,2.000000,-33.937553,...,1.000000,0.000000,0.000000,9.990000,-2.750000,1.000000,9.990000,7.490000,-4274.980000,9.990000
25%,2.000000,2.000000,7.000000,104.380000,0.000000,18.000000,3258.500000,725.000000,4.000000,18.265432,...,3258.500000,5.400000,0.040000,50.000000,0.080000,1.000000,119.980000,104.380000,7.000000,50.000000
50%,3.000000,4.000000,31.520000,163.990000,1.000000,29.000000,6457.000000,19380.000000,5.000000,33.144863,...,6457.000000,14.000000,0.100000,59.990000,0.270000,1.000000,199.920000,163.990000,31.520000,59.990000
75%,5.000000,4.000000,64.800000,247.400000,1.000000,45.000000,9779.000000,78207.000000,7.000000,39.279617,...,9779.000000,29.990000,0.160000,199.990000,0.360000,3.000000,299.950000,247.400000,64.800000,199.990000
max,6.000000,4.000000,911.800000,1939.990000,1.000000,76.000000,20757.000000,99205.000000,12.000000,48.781933,...,20757.000000,500.000000,0.250000,1999.990000,0.500000,5.000000,1999.990000,1939.990000,911.800000,1999.990000

In [11]:
df.describe(include="object")

C:\Users\ganesh\AppData\Local\Temp\ipykernel_17144\702825166.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  df.describe(include="object")

,Type,Delivery Status,Category Name,Customer City,Customer Country,Customer Fname,Customer Lname,Customer Segment,Customer State,Customer Street,Department Name,Market,Order City,Order Country,Order Region,Order State,Order Status,Product Name,Shipping Mode
count,180519,180519,180519,180519,180519,180519,180511,180519,180519,180519,180519,180519,180519,180519,180519,180519,180519,180519,180519
unique,4,4,50,563,2,782,1109,3,46,7458,11,5,3597,164,23,1089,9,118,4
top,DEBIT,Late delivery,Cleats,Caguas,EE. UU.,Mary,Smith,Consumer,PR,9126 Wishing Expressway,Fan Shop,LATAM,Santo Domingo,Estados Unidos,Central America,Inglaterra,COMPLETE,Perfect Fitness Perfect Rip Deck,Standard Class
freq,69295,98977,24551,66770,111146,65150,64104,93504,69373,122,66861,51594,2211,24840,28341,6722,59491,24515,107752

In [12]:
duplicate_count= df.duplicated().sum()
print("Duplicate rows:", duplicate_count)

Duplicate rows: 0

In [13]:
missing_values= df.isnull().sum()
missing_values[missing_values > 0]

Customer Lname      8
Customer Zipcode    3
dtype: int64

In [14]:
missing_percentage= (
    df.isnull().sum() / len(df) * 100
)

missing_summary= pd.DataFrame({
    "Missing Count": df.isnull().sum(),
    "Missing Percentge": missing_percentage
})

missing_summary= missing_summary[
    missing_summary["Missing Count"] > 0
]

missing_summary

                  Missing Count  Missing Percentge
Customer Lname                8           0.004432
Customer Zipcode              3           0.001662

In [15]:
TARGET= "Late_delivery_risk"

In [16]:
df[TARGET].value_counts()

Late_delivery_risk
1    98977
0    81542
Name: count, dtype: int64

In [17]:
df[TARGET].value_counts(normalize=True) * 100

Late_delivery_risk
1    54.829132
0    45.170868
Name: proportion, dtype: float64

In [18]:
df[TARGET].isnull().sum()

np.int64(0)

In [19]:
df_clean= df.copy()

In [20]:
df_clean= df_clean.drop_duplicates()

In [21]:
df_clean= df_clean.reset_index(drop=True)

In [22]:
df_clean= df_clean.dropna(subset=[TARGET])

In [23]:
print("Original shape:", df.shape)
print("Cleaned shape:", df_clean.shape)

Original shape: (180519, 40)
Cleaned shape: (180519, 40)

In [24]:
df_clean.isnull().sum().sort_values(
    ascending=False
).head(10)

Customer Lname                   8
Customer Zipcode                 3
Type                             0
Days for shipping (real)         0
Sales per customer               0
Delivery Status                  0
Days for shipment (scheduled)    0
Benefit per order                0
Category Id                      0
Late_delivery_risk               0
dtype: int64

In [25]:
required_columns= [
    "Late_delivary_risk",
    "Days for shipping (real)",
    "Days for shipment (scheduled)",
    "Shipping mode"
]

required_columns

['Late_delivary_risk',
 'Days for shipping (real)',
 'Days for shipment (scheduled)',
 'Shipping mode']

In [26]:
clean_df= df_clean.copy()
clean_df.shape

(180519, 40)

In [27]:
missing_required= [
    col for col in required_columns
    if col not in clean_df.columns
]

missing_required

['Late_delivary_risk', 'Shipping mode']

In [28]:
sorted(clean_df[TARGET].dropna().unique())

[np.int64(0), np.int64(1)]

In [29]:
clean_df["Shipping Mode"].value_counts

<bound method IndexOpsMixin.value_counts of 0         Standard Class
1         Standard Class
2         Standard Class
3         Standard Class
4         Standard Class
               ...
180514    Standard Class
180515    Standard Class
180516    Standard Class
180517    Standard Class
180518          Same Day
Name: Shipping Mode, Length: 180519, dtype: str>

In [30]:
numeric_columns=clean_df.select_dtypes(
    include= np.number
).columns.tolist()

len(numeric_columns)

21

In [31]:
categorical_columns= clean_df.select_dtypes(
    include="object"
).columns.tolist()

len(categorical_columns)

C:\Users\ganesh\AppData\Local\Temp\ipykernel_17144\3631601527.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  categorical_columns= clean_df.select_dtypes(

19

In [32]:
clean_df[
    clean_df["Order Item Quantity"] < 0
].shape

(0, 40)

In [33]:
clean_df[
    clean_df["Days for shipment (scheduled)"] < 0
].shape

(0, 40)

In [34]:
clean_df[
    clean_df["Days for shipping (real)"] < 0
].shape

(0, 40)

In [35]:
clean_df[
    [
        "Sales",
        "Order Item Total",
        "Order Profit Per Order",
        "Order Item Discount",
        "Order Item Discount Rate"  
    ]
].describe()

,Sales,Order Item Total,Order Profit Per Order,Order Item Discount,Order Item Discount Rate
count,180519.000000,180519.000000,180519.000000,180519.000000,180519.000000
mean,203.772092,183.107607,21.974989,20.664741,0.101668
std,132.273075,120.043668,104.433526,21.800901,0.070415
min,9.990000,7.490000,-4274.980000,0.000000,0.000000
25%,119.980000,104.380000,7.000000,5.400000,0.040000
50%,199.920000,163.990000,31.520000,14.000000,0.100000
75%,299.950000,247.400000,64.800000,29.990000,0.160000
max,1999.990000,1939.990000,911.800000,500.000000,0.250000

In [36]:
OUTPUT_DIR= PROJECT_ROOT / "outputs"
OUTPUT_DIR.mkdir(
    parents=True,
    exist_ok=True
)

In [37]:
CLEAN_DATA_PATH= OUTPUT_DIR / "APL_Logistics_cleaned.csv"

In [38]:
clean_df.to_csv(
    CLEAN_DATA_PATH,
    index=False
)

In [39]:
print("Saved cleaned dataset to:")
print(CLEAN_DATA_PATH)

Saved cleaned dataset to:
c:\Users\ganesh\Desktop\All Projects\Build Logistic Analysis Project\outputs\APL_Logistics_cleaned.csv

In [40]:
print("=" * 50)
print("DATA CLEANING COMPLETE")
print("=" * 50)
print("Original rows:", len(df))
print("Cleaned rows:", len(clean_df))
print("Columns:", len(clean_df.columns))
print("Duplicate rows:", clean_df.duplicated().sum())
print("Missing target:", clean_df[TARGET].isnull().sum())
print("Cleaned file:", CLEAN_DATA_PATH)

==================================================
DATA CLEANING COMPLETE
==================================================
Original rows: 180519
Cleaned rows: 180519
Columns: 40
Duplicate rows: 0
Missing target: 0
Cleaned file: c:\Users\ganesh\Desktop\All Projects\Build Logistic Analysis Project\outputs\APL_Logistics_cleaned.csv